import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — IFS Journal',
}

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: April 24, 2026</p>

      <div className="prose prose-neutral max-w-none space-y-6 text-foreground">
        <section>
          <h2 className="text-xl font-semibold mb-2">Not medical advice</h2>
          <p>
            IFS Journal is a journaling tool inspired by the Internal Family Systems therapy
            framework. It is not a medical device. It is not therapy. It is not a substitute for a
            licensed clinician. Content generated by the app (including parts analysis and part
            conversations) is produced by an AI model and may be wrong, incomplete, or inappropriate
            for your situation. If you are in crisis, contact emergency services or a crisis line
            (in the US: call or text 988).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Your account</h2>
          <p>
            You are responsible for keeping your password secret. You must be at least 16 years old
            to create an account. You must provide a valid email address and verify it before using
            the app.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Acceptable use</h2>
          <p>Don't use IFS Journal to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>send content that is illegal, abusive, or threatens others</li>
            <li>attempt to circumvent security controls, rate limits, or multi-tenant isolation</li>
            <li>build derivative products by scraping other users' data</li>
            <li>automate account creation or spam the service</li>
          </ul>
          <p>
            We may suspend or terminate accounts that violate these rules, abuse the service, or
            cause disproportionate cost to the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Your content</h2>
          <p>
            You own what you write. You grant us a limited license to process your content in order
            to operate the service (store it, run the IFS analysis, stream conversation responses,
            show it back to you). We never use your content to train any model.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Service availability</h2>
          <p>
            The app is provided "as is," without warranties of any kind. We may change, pause, or
            shut down features at any time. If the service is permanently discontinued we will
            attempt to give you reasonable notice and an opportunity to export your data.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, the operator is not liable for indirect,
            incidental, consequential, or punitive damages arising from your use of IFS Journal.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Changes</h2>
          <p>
            We may update these terms over time. Meaningful changes will be noted at the top of this
            page.
          </p>
        </section>
      </div>
    </main>
  )
}
